### ISSUE TITLE
Reaction conditions: Add thermodynamic activity to the aqueous system 

### ISSUE THREAD

**Issue by StephanM87** [StephanM87/Strenda-biocatalysis#21]

**Comment by PeterHalling** [comment]
With the exception of pH, this is not normally something that is set by the experimenter while putting together the reaction mixture. They will add specified concentrations of ingredients. Thermodynamic activities will result from how these ingredients interact with each other. If there is any information about activities it will come from measurements (so is perhaps data rather than metadata) - but I think it is very unusual to make such measurements. With appropriate models it may also be possible to estimate activities from the reported composition.

**Comment by StephanM87** [comment]
For me at least this sounds like the easiest solution. Therefore, I would put this issue on hold.
